
INSERT INTO public.pages (slug, title, hero_title, hero_subtitle, hero_image, blocks, in_nav, published, nav_label, nav_order) VALUES
('money-market', 'Money Market Savings', 'Grow your cash with a Money Market account', 'Tiered rates that reward higher balances — with the same everyday access you expect.',
 'https://images.unsplash.com/photo-1579621970588-a35d0e7ab9b6?w=1200&q=80',
 '[{"type":"features","title":"Why members choose Money Market","items":[{"title":"Tiered rates","body":"Higher balances earn higher yields — automatically."},{"title":"Everyday access","body":"Move funds anytime through online and mobile banking."},{"title":"Federally insured","body":"Your deposits are protected up to applicable limits."}]},{"type":"cta","title":"Open a Money Market account","button":"Get started","to":"/auth"}]'::jsonb,
 false, true, null, 0),
('certificates', 'Share Certificates', 'Lock in a rate. Watch it grow.', 'Terms from 3 months to 7 years with competitive dividends and low minimum deposits.',
 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80',
 '[{"type":"stats","items":[{"k":"3–84 mo","v":"Flexible terms"},{"k":"$1,000","v":"Low minimum"},{"k":"Fixed","v":"Guaranteed rate"}]},{"type":"features","title":"Certificate features","items":[{"title":"Guaranteed returns","body":"Your rate is locked for the life of the certificate."},{"title":"Ladder your savings","body":"Stagger terms to keep some cash accessible."},{"title":"IRA options","body":"Use certificates inside a Traditional or Roth IRA."}]}]'::jsonb,
 false, true, null, 0),
('credit-cards', 'Credit Cards', 'A card for every part of your life', 'Cash back, low rates, and no foreign transaction fees on select cards.',
 'https://images.unsplash.com/photo-1580508174046-170816f65662?w=1200&q=80',
 '[{"type":"tiles","title":"Explore our cards","items":[{"label":"Rewards Cards","icon":"card","to":"/rewards-cards"},{"label":"Low-Rate Cards","icon":"wallet","to":"/low-rate-cards"},{"label":"Business Cards","icon":"briefcase","to":"/business-cards"}]},{"type":"features","title":"What you get","items":[{"title":"Up to 2% cash back","body":"Earn on every purchase with select rewards cards."},{"title":"No annual fee","body":"On most consumer cards."},{"title":"Fraud protection","body":"24/7 monitoring and zero-liability coverage."}]}]'::jsonb,
 false, true, null, 0),
('student-loans', 'Student Loans', 'Finance your education with confidence', 'Undergraduate, graduate, and refinance options with competitive fixed and variable rates.',
 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&q=80',
 '[{"type":"features","title":"Student loan options","items":[{"title":"Undergraduate loans","body":"Cover tuition, housing, books, and more."},{"title":"Graduate loans","body":"Loans tailored to advanced degrees."},{"title":"Refinance","body":"Consolidate existing student debt at a lower rate."}]},{"type":"cta","title":"Explore student loan options","button":"See rates","to":"/auth"}]'::jsonb,
 false, true, null, 0),
('mortgage', 'Mortgage', 'Home loans built around your life', 'Fixed-rate, adjustable-rate, jumbo, and 100% financing options for eligible members.',
 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80',
 '[{"type":"tiles","title":"Mortgage options","items":[{"label":"Home Loans","icon":"home","to":"/home-loans"},{"label":"Refinance","icon":"bank","to":"/refinance"},{"label":"HELOC","icon":"wallet","to":"/heloc"},{"label":"First-Time Homebuyer","icon":"heart","to":"/first-time-homebuyer"}]},{"type":"features","title":"Why Meridian for your mortgage","items":[{"title":"100% financing options","body":"A great choice for first-time homebuyers."},{"title":"Dedicated loan officers","body":"One point of contact from application to closing."},{"title":"Fast pre-approval","body":"Know what you can afford before you shop."}]}]'::jsonb,
 false, true, null, 0),
('refinance', 'Mortgage Refinance', 'Lower your rate, shorten your term', 'Refinance to reduce your monthly payment, tap equity, or pay your home off faster.',
 'https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200&q=80',
 '[{"type":"features","title":"Refinance benefits","items":[{"title":"Lower monthly payment","body":"Reduce your rate and free up cash flow."},{"title":"Cash-out options","body":"Use home equity for major expenses."},{"title":"Shorter term","body":"Pay off your home sooner and save on interest."}]}]'::jsonb,
 false, true, null, 0),
('heloc', 'Home Equity Line of Credit', 'Put your home equity to work', 'Flexible access to your home''s equity for renovations, education, or large expenses.',
 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
 '[{"type":"features","title":"HELOC features","items":[{"title":"Draw as you need","body":"Access funds during your draw period."},{"title":"Interest-only payments","body":"Available during the draw period."},{"title":"Competitive rates","body":"Variable rates tied to prime."}]}]'::jsonb,
 false, true, null, 0),
('first-time-homebuyer', 'First-Time Homebuyer', 'Set yourself up for homebuying success', 'We''ll help you understand the path to homeownership — from savings to closing.',
 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
 '[{"type":"features","title":"We''ll guide you through","items":[{"title":"Affordability","body":"Understand what you can comfortably afford."},{"title":"Pre-approval","body":"Shop with confidence knowing your budget."},{"title":"Down payment options","body":"Explore programs including 100% financing."}]},{"type":"cta","title":"Start your homebuying journey","button":"Talk to a loan officer","to":"/contact"}]'::jsonb,
 false, true, null, 0),
('insurance', 'Insurance', 'Protect what matters most', 'Auto, home, life, and specialty coverage through trusted partners.',
 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80',
 '[{"type":"features","title":"Coverage options","items":[{"title":"Auto insurance","body":"Competitive rates from top-rated carriers."},{"title":"Home & renters","body":"Protect your home and belongings."},{"title":"Life insurance","body":"Term and whole-life policies for every stage."}]}]'::jsonb,
 false, true, null, 0),
('business-loans', 'Business Loans', 'Fuel your business growth', 'Term loans, lines of credit, equipment financing, and commercial real estate loans.',
 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80',
 '[{"type":"features","title":"Business lending options","items":[{"title":"Term loans","body":"Fixed rates and predictable payments."},{"title":"Lines of credit","body":"Flexible working capital when you need it."},{"title":"Equipment financing","body":"Preserve cash while acquiring key equipment."}]}]'::jsonb,
 false, true, null, 0),
('eligibility', 'Membership Eligibility', 'Am I eligible for membership?', 'Check whether you or a family member qualifies to join Meridian.',
 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&q=80',
 '[{"type":"features","title":"Who can join","items":[{"title":"Family members","body":"Immediate family of existing members are eligible."},{"title":"Community partners","body":"Employees of select partner organizations."},{"title":"Local residents","body":"Residents of qualifying communities."}]},{"type":"cta","title":"Check your eligibility","button":"Enroll now","to":"/auth"}]'::jsonb,
 false, true, null, 0),
('benefits', 'Member Benefits', 'Earn and save more as a member', 'Our members can earn and save hundreds each year through better rates and fewer fees.',
 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80',
 '[{"type":"stats","items":[{"k":"$473","v":"Average annual benefit"},{"k":"0","v":"Monthly checking fees on core accounts"},{"k":"24/7","v":"Member support"}]},{"type":"features","title":"Why members stay","items":[{"title":"Better rates","body":"Competitive dividends on deposits and lower loan rates."},{"title":"Fewer fees","body":"Straightforward pricing with no hidden costs."},{"title":"Personal service","body":"Talk to a real person, day or night."}]}]'::jsonb,
 false, true, null, 0),
('making-cents', 'MakingCents', 'Financial resources for every stage', 'Guides, calculators, and articles on homeownership, savings, budgeting, and military life.',
 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=1200&q=80',
 '[{"type":"promos","title":"Featured resources","items":[{"title":"A guide to first-time homebuyer programs","body":"More resources than you might think.","cta":"Read the guide","to":"/first-time-homebuyer"},{"title":"A month-by-month guide to finding deals","body":"Time your purchases throughout the year.","cta":"See the guide","to":"/making-cents"},{"title":"Establishing your finances after a PCS","body":"Tips after a Permanent Change of Station move.","cta":"Read more","to":"/making-cents"}]},{"type":"features","title":"Popular topics","items":[{"title":"Home ownership","body":"Affordability, mortgages, and refinancing."},{"title":"Savings & budgeting","body":"Practical guides to build healthy habits."},{"title":"Business","body":"Tips for owners and small businesses."}]}]'::jsonb,
 false, true, null, 0)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  hero_title = EXCLUDED.hero_title,
  hero_subtitle = EXCLUDED.hero_subtitle,
  hero_image = EXCLUDED.hero_image,
  blocks = EXCLUDED.blocks,
  published = true;
